### PR TITLE
Fix homepage spacing

### LINKED ISSUE #259: Make the two main boxes the same height on the landing page
Adjust spacing on the homepage boxes so that they are equal. 

Screen Shot 2021-07-14 at 4 07 41 PM

### PR DESCRIPTION
**Pull request by nitinsubz**
Make the two main boxes the same height by adding white space above the blue button.

Fixes #259

### CODE REVIEW

File: client/src/js/agreement/CreateAgreementContainer.jsx [hunk 1]
```diff
@@ -41,6 +41,7 @@ function CreateAgreementContainer () {
                   <li>I'm making contributions of code I've created in my free time (not under contract),
                     and I hold the copyright on my contributions.
                   </li>
+                  <br></br><br></br><br></br>
```
Comment (teone) [inline client/src/js/agreement/CreateAgreementContainer.jsx:44]: Adding new lines will only work on some screen resolution. The `<Grid item xs={12} md={6}>` items are the same height already, so I would look into making the card full height via `css`
Screen Shot 2021-07-15 at 4 00 01 PM

**Review by teone — CHANGES_REQUESTED** [review]

File: client/src/js/agreement/CreateAgreementContainer.jsx (hunk 1 above)
Comment (teone) [reply client/src/js/agreement/CreateAgreementContainer.jsx:44]: For example: https://stackoverflow.com/questions/55824260/same-height-cards-in-material-ui

**Review by teone — APPROVED** [review]
